### ISSUE TITLE
Do I need to upgrade the GLIBC version of ubuntu20.04 to run properly?

### ISSUE THREAD

**Issue by kinger2023** [pepenetsocial/pepenet#21]
meirong@OS-20230306EWPM:~/pepenet$ ./pepenetd-linux-x86_64-v0.2.0.0-beta
./pepenetd-linux-x86_64-v0.2.0.0-beta: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./pepenetd-linux-x86_64-v0.2.0.0-beta)
./pepenetd-linux-x86_64-v0.2.0.0-beta: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./pepenetd-linux-x86_64-v0.2.0.0-beta)
./pepenetd-linux-x86_64-v0.2.0.0-beta: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./pepenetd-linux-x86_64-v0.2.0.0-beta)
meirong@OS-20230306EWPM:~/pepenet$ ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.9) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

**Comment by azx19** [comment]
I built this as a static binary so it should work (not sure if system libraries get linked in as well though). Maybe consider running it in docker (ubuntu 22.04) if you don't want to upgrade to ubuntu 22.04. It was built on ubuntu 22.04 so maybe there are some problems. If you try running it in docker please let me know if you still have problems.

**Comment by azx19** [comment]
Maybe a quick fix for you:
I installed docker and pulled ubuntu 22.04.
When I ran pepenet-wallet-cli It was missing libunbound 8 (not sure how though because it was linked statically)
I fixed this by running apt install libunbound8.
![image](https://github.com/pepenetsocial/pepenet/assets/131379442/a857dade-adad-4a5e-b565-4b60e7b79fc1)

**Comment by kinger2023** [comment]
2023-09-03 20:26:46.530 I Binding on 127.0.0.1 (IPv4):18081
2023-09-03 20:26:47.063 I core RPC server initialized OK on port: 18081
2023-09-03 20:26:47.064 I Starting core RPC server...
2023-09-03 20:26:47.065 I core RPC server started ok
2023-09-03 20:26:47.065 I Starting p2p net loop...
2023-09-03 20:26:48.066 I
2023-09-03 20:26:48.066 I **********************************************************************
2023-09-03 20:26:48.066 I The daemon will start synchronizing with the network. This may take a long time to complete.
2023-09-03 20:26:48.066 I
2023-09-03 20:26:48.066 I You can set the level of process detailization through "set_log <level|categories>" command,
2023-09-03 20:26:48.066 I where <level> is between 0 (no details) and 4 (very verbose), or custom category based levels (eg, *:WARNING).
2023-09-03 20:26:48.066 I
2023-09-03 20:26:48.066 I Use the "help" command to see the list of available commands.
2023-09-03 20:26:48.066 I Use "help <command>" to see a command's documentation.
2023-09-03 20:26:48.066 I **********************************************************************
2023-09-03 20:26:56.607 W Invalid DNSSEC TXT record signature for updates.pepenetpulse.org: validation failure <updates.pepenetpulse.org. TXT IN>: no signatures from 172.27.160.1 for trust anchor . while building chain of trust
2023-09-03 20:27:23.180 W WARNING: no two valid DNS TXT records were received

**Comment by azx19** [comment]
I get the same error on ubuntu 20.04 (focal)
![image](https://github.com/pepenetsocial/pepenet/assets/131379442/c4c261ad-2e0d-453a-9798-e1c8bd6dd8d5)
static linking of glibc is discouraged (not sure why yet)
link: https://stackoverflow.com/questions/57476533/why-is-statically-linking-glibc-discouraged
One more useful link that explains that even monero can't be fully statically linked (still needs libunbound)
https://monero.stackexchange.com/questions/10208/can-monero-be-compiled-linked-statically

Therefore I suggest the following steps/options:
a) if you don't want to upgrade to ubuntu 22.04 (although it's not a bad idea to do so) you should install docker and run the 22.04 image
b) upgrade to 22.04

in both cases just install libunbound: sudo apt install libunbound8

**Comment by kinger2023** [comment]
apt update
apt install libunbound8 is ok。The problem you're talking about, I've fixed it, but the inability to sync is a problem

**Comment by kinger2023** [comment]
status
Height: 1/1 (100.0%) on mainnet, not mining, net hash 0 H/s, v1 (next fork in 9 blocks), 0(out)+0(in) connections, uptime 0d 0h 3m 41s

**Comment by azx19** [comment]
Is your local network behind a router/firewall or are you using a VPS ?

**Comment by azx19** [comment]
Try placing one of the two configuration files in ~/.pepenet. rename to pepenet.conf and maybe remove the mining address
[](https://github.com/azx19/pepenet-config). use the NAT if you are on your home network or the VPS if you are using a VPS

**Comment by kinger2023** [comment]
I use a home network, not a vps

**Comment by azx19** [comment]
> I use a home network, not a vps

I know this can be a serious pain. I had problems too when I was setting up the mainnet. I had to enable port forwarding on my router. That reddit post (link above) can help you out with that. It also has a link to a monero page that describes how to setup a monero node.

If you don't have the option to manage your router you should consider running your node on a VPS (really cheap about 8$ a month does the job) I'm using contabo and I like my setup. I mine over there and use the wallet on my laptop /pc at home.

**Comment by kinger2023** [comment]
I do run under docker, do I need to edit the entire file? pepenet.conf

**Comment by azx19** [comment]
Current seed node status:
![image](https://github.com/pepenetsocial/pepenet/assets/131379442/ad2223e7-8c32-4582-a9d1-579a8bb3686e)

**Comment by kinger2023** [comment]
What is your node ip, I bundle the node to start the test

**Comment by azx19** [comment]
yes. you need that file in ~/.pepenet (make the folder first) place the file there. When you run pepenetd with no arguments it will just look for the config file in that folder.

Also make sure port 18080 is forwarded on your router. And that this port if forwarded to your docker container: [stackoverflow](https://stackoverflow.com/questions/17770902/forward-host-port-to-docker-container)

maybe just add the --net=host to your docker run command

**Comment by azx19** [comment]
> What is your node ip, I bundle the node to start the test

ip: 5.189.149.83
port: 18080

**Comment by kinger2023** [comment]
ok Ah, you may not be very clear, I come from mainland China, need a vpn to use, I tried to turn off the vpn test. I've started syncing, but I didn't do anything before syncing

**Comment by kinger2023** [comment]
167.86.93.181

**Comment by azx19** [comment]
can you share a screenshot of the sync please ? Is it ok now ?

**Comment by kinger2023** [comment]
![image](https://github.com/pepenetsocial/pepenet/assets/127290850/b57aeac9-2673-45bc-8d75-88bfd4dd2df6)

**Comment by azx19** [comment]
awesome :). Make sure you're mining to your own address. The pepenet.conf on github is just a dummy address.
Just confirm the problem is resolved. If you have any more problems just make a new issue or go to r/pepenet.

**Comment by kinger2023** [comment]
![image](https://github.com/pepenetsocial/pepenet/assets/127290850/ceeb0eed-496d-482d-aef2-7641a1408991)
I've already received the mined coins. There's no problem

**Comment by azx19** [comment]
Amazing, glad to hear. Consider joining r/pepenet I'm glad to have you as the first co-miner :) Maybe make a pep
